name: Run script.sh

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script.sh
      run: |
        chmod +x script.sh
        ./script.sh > src/assets/articulos/nombres.json
